export const seedCategories = [
  { name: "Men", description: "Sharp grooming rituals for modern gentlemen." },
  { name: "Women", description: "Luxury beauty experiences designed to glow." },
];

export const seedSubCategories = {
  Men: ["Hair", "Beard", "Facial", "Massage"],
  Women: ["Hair", "Makeup", "Bridal", "Facial", "Spa"],
};

export const seedServices = [
  {
    category: "Men",
    subCategory: "Hair",
    title: "Premium Hair Cut",
    description: "Precision haircut finished with a luxury wash, dry, and styling ritual.",
    duration: "30 min",
    price: 299,
    image: "https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Men",
    subCategory: "Hair",
    title: "Executive Hair Spa",
    description: "Deep nourishment therapy for refined texture, shine, and scalp comfort.",
    duration: "45 min",
    price: 899,
    image: "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Men",
    subCategory: "Beard",
    title: "Royal Beard Sculpt",
    description: "Detailed beard shaping with hot towel prep and premium beard serum finish.",
    duration: "25 min",
    price: 249,
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Men",
    subCategory: "Facial",
    title: "Gentleman's Gold Facial",
    description: "A revitalizing facial crafted to brighten, hydrate, and restore confidence.",
    duration: "50 min",
    price: 1299,
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Men",
    subCategory: "Massage",
    title: "Stress Relief Head Massage",
    description: "A calming scalp and neck therapy using aromatic oils and slow pressure work.",
    duration: "30 min",
    price: 499,
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Hair",
    title: "Signature Hair Styling",
    description: "Elegant styling with a premium blow dry for events, dinners, and celebrations.",
    duration: "45 min",
    price: 799,
    image: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Hair",
    title: "Luxury Keratin Ritual",
    description: "Smoothening service that softens frizz and adds luminous, lasting polish.",
    duration: "120 min",
    price: 3499,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Makeup",
    title: "HD Party Makeup",
    description: "Camera-ready glam tailored to your style, outfit, and skin tone.",
    duration: "75 min",
    price: 2499,
    image: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Bridal",
    title: "Bridal Radiance Package",
    description: "A complete premium bridal look with consultation, makeup, hair, and draping.",
    duration: "180 min",
    price: 9999,
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Facial",
    title: "24K Glow Facial",
    description: "An indulgent brightening facial for hydrated, lifted, and event-ready skin.",
    duration: "60 min",
    price: 1699,
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80",
  },
  {
    category: "Women",
    subCategory: "Spa",
    title: "Aroma Luxury Spa Therapy",
    description: "A soothing full-body experience created for deep relaxation and glow.",
    duration: "90 min",
    price: 2999,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=80",
  },
];