export const seedCategories = [
  // Male Categories
  { name: "Hair", gender: "Male", displayOrder: 1, isActive: true },
  { name: "Beard", gender: "Male", displayOrder: 2, isActive: true },
  { name: "Facial", gender: "Male", displayOrder: 3, isActive: true },
  { name: "Massage", gender: "Male", displayOrder: 4, isActive: true },
  // Female Categories
  { name: "Hair", gender: "Female", displayOrder: 1, isActive: true },
  { name: "Makeup", gender: "Female", displayOrder: 2, isActive: true },
  { name: "Waxing", gender: "Female", displayOrder: 3, isActive: true },
  { name: "Bridal", gender: "Female", displayOrder: 4, isActive: true },
  { name: "Nails", gender: "Female", displayOrder: 5, isActive: true },
];

export const seedServices = [
  // Male Services
  {
    categoryName: "Hair",
    gender: "Male",
    name: "Premium Hair Cut",
    description: "Precision haircut finished with a luxury wash, dry, and styling ritual.",
    duration: "30 min",
    price: 299,
    mrp: 399,
    image: "https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Hair",
    gender: "Male",
    name: "Executive Hair Spa",
    description: "Deep nourishment therapy for refined texture, shine, and scalp comfort.",
    duration: "45 min",
    price: 899,
    mrp: 1099,
    image: "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Beard",
    gender: "Male",
    name: "Royal Beard Sculpt",
    description: "Detailed beard shaping with hot towel prep and premium beard serum finish.",
    duration: "25 min",
    price: 249,
    mrp: 299,
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Facial",
    gender: "Male",
    name: "Gentleman's Gold Facial",
    description: "A revitalizing facial crafted to brighten, hydrate, and restore confidence.",
    duration: "50 min",
    price: 1299,
    mrp: 1599,
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Massage",
    gender: "Male",
    name: "Stress Relief Head Massage",
    description: "A calming scalp and neck therapy using aromatic oils and slow pressure work.",
    duration: "30 min",
    price: 499,
    mrp: 599,
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  // Female Services
  {
    categoryName: "Hair",
    gender: "Female",
    name: "Signature Hair Styling",
    description: "Elegant styling with a premium blow dry for events, dinners, and celebrations.",
    duration: "45 min",
    price: 799,
    mrp: 999,
    image: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Hair",
    gender: "Female",
    name: "Luxury Keratin Ritual",
    description: "Smoothening service that softens frizz and adds luminous, lasting polish.",
    duration: "120 min",
    price: 3499,
    mrp: 4499,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Makeup",
    gender: "Female",
    name: "HD Party Makeup",
    description: "Camera-ready glam tailored to your style, outfit, and skin tone.",
    duration: "75 min",
    price: 2499,
    mrp: 2999,
    image: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
  {
    categoryName: "Bridal",
    gender: "Female",
    name: "Bridal Radiance Package",
    description: "A complete premium bridal look with consultation, makeup, hair, and draping.",
    duration: "180 min",
    price: 9999,
    mrp: 12499,
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
    isActive: true,
  },
];